name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: ec2-18-116-230-25.us-east-2.compute.amazonaws.com  # Using the actual DNS
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Define this secret in your GitHub repo settings

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 600 mykey.pem
          
          # Copy the files from the current work dir into the EC2 instance, under ~/NetflixMovieCatalog.
          scp -o StrictHostKeyChecking=no -i mykey.pem -r * ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog
          
          # Check if deploy.sh exists
          if [ ! -f ~/NetflixMovieCatalog/deploy.sh ]; then
            echo "deploy.sh not found!"
            exit 1
          fi

          # Connect to your EC2 instance and execute the deploy.sh script
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash ~/NetflixMovieCatalog/deploy.sh"

      - name: Cleanup
        run: |
          rm mykey.pem
